name: Claude Code Assistant

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  # Respond to @claude mentions
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  claude-assistant:
    # Only run when @claude is mentioned or for PR events
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better context

      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Automatically detect mode based on context
          # For PRs, perform automatic review
          prompt: |
            ${{ github.event_name == 'pull_request' && '/review --comprehensive' || '' }}
          claude_args: |
            --max-turns 15
            --model claude-sonnet-4-20250514
            --system-prompt "You have access to specialized subagents in .claude/agents/ for architecture, React, TypeScript, bug detection, and more. Use them when appropriate."